"""Auto-onboarding: scaffold a `.euron/` wrapper the first time the agent works in
a project, so memory, a skill, and a project doc exist by default - no setup.

Creates (only what's missing):
    .euron/AGENTS.md                      - project memory / rules (auto-loaded)
    .euron/PROJECT.md                     - a project overview doc (the agent's own MD)
    .euron/skills/explore-codebase/SKILL.md  - a starter skill for understanding the repo

Everything is detected from the repo (stack, build/test/lint commands), so the
files are useful immediately and key-free.
"""
from __future__ import annotations

import json
from pathlib import Path


def detect_project(workspace: str) -> dict:
    root = Path(workspace)
    info: dict = {"name": root.name, "stack": [], "build": [], "test": [],
                  "lint": [], "run": [], "git": (root / ".git").exists()}

    def add(cat: str, cmd: str):
        if cmd not in info[cat]:
            info[cat].append(cmd)

    if (root / "pyproject.toml").exists() or (root / "setup.py").exists() or (root / "requirements.txt").exists():
        info["stack"].append("Python")
        if (root / "requirements.txt").exists():
            add("build", "pip install -r requirements.txt")
        if (root / "pyproject.toml").exists():
            add("build", "pip install -e .")
        add("test", "pytest")
    pkg = root / "package.json"
    if pkg.exists():
        info["stack"].append("Node.js")
        try:
            scripts = json.loads(pkg.read_text(encoding="utf-8")).get("scripts", {})
            cat = {"build": "build", "test": "test", "lint": "lint", "dev": "run", "start": "run"}
            for k, c in cat.items():
                if k in scripts:
                    add(c, f"npm run {k}")
        except Exception:
            pass
    if (root / "go.mod").exists():
        info["stack"].append("Go"); add("build", "go build ./..."); add("test", "go test ./...")
    if (root / "Cargo.toml").exists():
        info["stack"].append("Rust"); add("build", "cargo build"); add("test", "cargo test")
    if (root / "pom.xml").exists():
        info["stack"].append("Java/Maven"); add("build", "mvn compile"); add("test", "mvn test")
    if (root / "build.gradle").exists() or (root / "build.gradle.kts").exists():
        info["stack"].append("Gradle"); add("build", "gradle build"); add("test", "gradle test")
    if (root / "Gemfile").exists():
        info["stack"].append("Ruby")
    if (root / "composer.json").exists():
        info["stack"].append("PHP")
    # top-level layout (a few entries)
    try:
        entries = sorted(p.name for p in root.iterdir()
                         if not p.name.startswith(".") and p.name not in ("node_modules", "venv"))
        info["layout"] = entries[:20]
    except Exception:
        info["layout"] = []
    return info


def needs_scaffold(workspace: str) -> bool:
    return not (Path(workspace) / ".euron").exists()


def _list(items: list, fallback: str = "(detect / fill in)") -> str:
    return "\n".join(f"- `{x}`" for x in items) if items else f"- {fallback}"


def _agents_md(info: dict) -> str:
    stack = ", ".join(info["stack"]) or "(unknown)"
    return f"""# Project memory - {info['name']}

Auto-loaded into the agent's context. Edit freely; this is the source of truth
for how to work in this repo.

## Stack
{stack}

## Commands
**Build/install**
{_list(info['build'])}
**Test**
{_list(info['test'])}
**Lint**
{_list(info['lint'])}
**Run/dev**
{_list(info['run'])}

## Conventions
- (e.g. code style, branch naming, files to never touch)

## Notes
- (anything the agent should always know about this project)
"""


def _project_md(info: dict) -> str:
    layout = "\n".join(f"- {x}" for x in info.get("layout", [])) or "- (run `list_files`)"
    return f"""# {info['name']} - project overview

> Auto-generated by Euron Agent onboarding. Enrich it by asking the agent to
> "study this codebase and update .euron/PROJECT.md".

**Stack:** {', '.join(info['stack']) or 'unknown'}
**Git:** {'yes' if info['git'] else 'no'}

## Top-level layout
{layout}

## How to build & test
{_list(info['build'] + info['test'])}

## Architecture notes
- (the agent fills these in as it learns the codebase)
"""


def _skill_md(info: dict) -> str:
    return f"""---
description: How to explore and safely work in the {info['name']} codebase.
---

# Explore the {info['name']} codebase

When asked to understand, change, or debug this project:

1. Read `.euron/PROJECT.md` and `.euron/AGENTS.md` first for stack and commands.
2. Map the structure with `list_files` and `glob`; read entry points and configs.
3. Use `search_text` to locate symbols before editing; prefer `edit_file`.
4. After changes, run the test command from memory and fix failures.
5. Keep changes minimal and match existing style.

Stack: {', '.join(info['stack']) or 'unknown'}
"""


def scaffold(workspace: str) -> list[str]:
    """Create the .euron scaffold (only files that don't already exist)."""
    root = Path(workspace)
    info = detect_project(workspace)
    euron = root / ".euron"
    (euron / "skills" / "explore-codebase").mkdir(parents=True, exist_ok=True)
    created: list[str] = []

    mem = euron / "AGENTS.md"
    has_memory = any((root / n).exists() for n in ("AGENTS.md", "EURON.md", "CLAUDE.md"))
    if not mem.exists() and not has_memory:
        mem.write_text(_agents_md(info), encoding="utf-8")
        created.append(".euron/AGENTS.md")

    proj = euron / "PROJECT.md"
    if not proj.exists():
        proj.write_text(_project_md(info), encoding="utf-8")
        created.append(".euron/PROJECT.md")

    skill = euron / "skills" / "explore-codebase" / "SKILL.md"
    if not skill.exists():
        skill.write_text(_skill_md(info), encoding="utf-8")
        created.append(".euron/skills/explore-codebase/SKILL.md")

    return created
